### ISSUE TITLE
Certain video files don't work on OS X

### ISSUE THREAD

**Issue by gohai** [gohai/processing-glvideo#12]
These two video files aren't currently working on OS X using the wip2 branch. They work from the command line on OS X, as well as on the Raspberry Pi using the 1.0.2 release.

[waters.zip](https://github.com/gohai/processing-glvideo/files/440669/waters.zip)

What might be relevant: the line `/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-9.1.12/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3` appears in the output only after the sketch is closed, whereas it is being printed immediately when using the gst-launch. (Could be related to #9)

**Comment by gohai** [comment]
This file also isn't working, albeit I've only tried with macOS.

[boulez.zip](https://github.com/gohai/processing-glvideo/files/587256/boulez.zip)

It might be that `texture-target: rectangle` is the culprit, see this thread [here](https://lists.freedesktop.org/archives/gstreamer-devel/2016-November/061489.html).

**Comment by gohai** [comment]
Fixed by 9ec8f9ab5318b2a375af5f44ef853c156dd9b733

**Comment by DeqingSun** [comment]
Hi gohai.

I believed I has the same issue. How can I apply this fix?

**Comment by gohai** [comment]
@DeqingSun Planning on releasing an updated version within a week or so.
