### ISSUE TITLE
playing in reverse, controlling speed and ogg videos

### ISSUE THREAD

**Issue by smarques** [gohai/processing-glvideo#23]
Hi I am trying to use this library to control video speed and play it in reverse under some conditions.
I always get themessage "Can not set speed to -1.0" if I try to reverse.
I read that not all codecs support this so I tried with OGG video (*.ogv)
but I get the message
Missing decoder: Ogg (video/ogg)

Any hints on how to gain a fine control of speed and playing backwards?
Also is there any way to add the missing decoder?

TIA
sergio

**Comment by gohai** [comment]
@smarques 
When I tried negative playback rates, GStreamer [froze for me](https://github.com/gohai/processing-glvideo/blob/9ec8f9ab5318b2a375af5f44ef853c156dd9b733/src/native/impl.c#L754). Feel free to investigate this further if you're interested, and please send a PR if you make it work :)

I believe Ogg decoding would necessitate having `libogg` installed on the system that the library gets installed to, so I'd recommend just using mp4 files instead.

Other playback speeds above 0.0 should work, by the way.
