### ISSUE TITLE
SimpleCapture example output shifted

### ISSUE THREAD

**Issue by alberto2000** [gohai/processing-glvideo#25]
On a Raspberry Pi 3 running newest Jessie the output of SimpleCapture example is slightly shifted around 40px/40px

![alt text](http://i.imgur.com/n2nxof8.jpg "Slightly shifted camera output")

**Comment by gohai** [comment]
Disabling overscan fixes this: see https://www.raspberrypi.org/documentation/configuration/raspi-config.md
