### ISSUE TITLE
Video Playback on raspberry pi 3 - libEGL warning: DRI2: failed to authenticate

### ISSUE THREAD

**Issue by nullxff** [gohai/processing-glvideo#3]
Hi!

I Installed the processing-glvideo library via the processing library manager. But I am not able to play any video. I get the following error:

libEGL warning: DRI2: failed to authenticate
/usr/local/lib/processing-3.1.1/java/bin/java: symbol lookup error: /tmp/jogamp_0000/file_cache/jln2465173736968517657/jln7418784907119433744/natives/linux-armv6hf/libnewt.so: undefined symbol: bcm_host_init
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.

I've tried your expamples for playing single video or two videos...
Other Sketches without the lib are running well... 

Ive already googled and found that others have similar problems, but I wasn't able to fix it.
Would be nice if you could explain what to do, to get your nice library running!

Cheers!

**Comment by gohai** [comment]
That's because of an issue with Raspbian. Try running `sudo aptitude remove libgles2-mesa`. See also [here](https://github.com/processing/processing/wiki/Raspberry-Pi#download)
