### ISSUE TITLE
mov.Framerate() not working

### ISSUE THREAD

**Issue by corbinyo** [gohai/processing-glvideo#36]
I get the error `The global variable "frameRate"` does not exist  after I ported in the Frames example from the processing library.

Can anyone tell me why?

**Comment by gohai** [comment]
@corbinyo Use `frameRate()`.

**Comment by corbinyo** [comment]
Is it possible to use with a perimeter such as frameRate(24) ?
I have a sketch set up where I am trying to scrub through a video with a tactile button.
As it is working right now it only shows a new frame for every 10 button clicks...

**Comment by gohai** [comment]
@corbinyo Have a look at the documentation that comes with the library. (`speed(rate)`).
