### ISSUE TITLE
Ubuntu 17.04 x64 libglvideo.so: undefined symbol: gst_init_check

### ISSUE THREAD

**Issue by senisioi** [gohai/processing-glvideo#39]
For ubuntu 17.04 x64 the libglvideo released from processing was compiled against 1.08 and the repository default is 1.10, so I had to compile this locally. One thing that I noticed, though, was that I had to add the link flags at the end, so I changed line 63 in the src/native/Makefile from
``
$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@ 
``
to
``
$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
``
Otherwise, the linking wouldn't be done correctly and processing would yield:
_undefined symbol: gst_init_check_
Looks like some other folks had this problem with the order of the flags in the past: https://stackoverflow.com/questions/8347676/issues-linking-against-gstreamer-libraries-ubuntu-11-10

Not sure if it's an issue or if changing the order of the flags won't affect the compilation on other platforms, but I'm posting it in case somebody else has this problem.

**Comment by gohai** [comment]
Thanks, Sergiu, for the report. I've made the suggested change in 15380c2fe8637ae483688d2ff112ee83e05542c4.
