### ISSUE TITLE
OSX: no such element factory "avfvideosrc", Could not open capture device avfvideosrc device-index=0

### ISSUE THREAD

**Issue by agatheblues** [gohai/processing-glvideo#40]
Hello,

First, thanks for the work on that library !

I'm trying to set up a UDP server on a Raspberry Pi, that would stream video images from the Rpi camera module on the network. At the moment, I have a prototype that uses processing-glvideo library, that I'm not yet running on the rpi but on macOS High Sierra, which _works_ (although there is this red FIXME error) if I run it in **Eclipse**:

```0:00:00.035770000  1267 0x7fc932ad0610 WARN                 default gstdevicemonitor.c:372:GList *gst_device_monitor_get_devices(GstDeviceMonitor *):<devicemonitor0> No providers match the current filters
GLVideo: Device enumeration is currently not available on macOS. The device returned is a pure guesstimate.
0:00:00.150942000  1267 0x7fc92ec0b800 FIXME                default gstutils.c:3902:gchar *gst_pad_create_stream_id_internal(GstPad *, GstElement *, const gchar *):<avfvideosrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
Final caps: video/x-raw(memory:GLMemory), width=(int)320, height=(int)240, format=(string)RGBA, framerate=(fraction)30/1, texture-target=(string)2D
```

When I say it works, I mean that my mac camera lights on, and I can see the webcam image in the processing sketch.

However, when I made the program a **runnable jar**, and execute it from my terminal, I get the following error:

```$ java -jar -Djava.library.path="lib/processing/macosx"  rpi-camera-service.jar
0:00:00.013288000  1343 0x7fa53c875cc0 WARN                 default gstdevicemonitor.c:372:GList *gst_device_monitor_get_devices(GstDeviceMonitor *):<devicemonitor0> No providers match the current filters
GLVideo: Device enumeration is currently not available on macOS. The device returned is a pure guesstimate.
Number of devices: 1
First device: avfvideosrc device-index=0
0:00:00.015523000  1343 0x7fa53c875cc0 WARN     GST_ELEMENT_FACTORY gstelementfactory.c:456:GstElement *gst_element_factory_make(const gchar *, const gchar *): no such element factory "avfvideosrc"!
0:00:00.015595000  1343 0x7fa53c875cc0 ERROR           GST_PIPELINE grammar.y:816:int priv_gst_parse_yyparse(void *, graph_t *): geen element "avfvideosrc"
Could not parse source element avfvideosrc device-index=0: geen element "avfvideosrc"
Exception in thread "Thread-2" java.lang.RuntimeException: Could not open capture device avfvideosrc device-index=0
	at gohai.glvideo.GLCapture.<init>(Unknown Source)
	at gohai.glvideo.GLCapture.<init>(Unknown Source)
	at NetworkMotionTracker.setup(NetworkMotionTracker.java:76)
	at processing.core.PApplet.handleDraw(PApplet.java:2374)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:731)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)`
```

Do you have any clue why there would be a difference between running it inside Eclipse and running it in the terminal ? Is this error bound to GLvideo or to gstreamer? Would this error be different on another OS ?

**Comment by gohai** [comment]
Hi @agatheblues!

I don't know exactly what is happening, but I am pretty sure I know what is wrong: the library tells GStreamer where to look for its plugins via an environment variable. This happens [here](https://github.com/gohai/processing-glvideo/blob/master/src/gohai/glvideo/GLVideo.java#L133). For _some_ reason, your directory layout seems to be different than what this code expects.

I honestly have never used Eclipse, and really only care about the library working from within the Processing IDE, which is hard enough. (The library path for exported applications is e.g. [different](https://github.com/gohai/processing-glvideo/blob/master/src/gohai/glvideo/GLVideo.java#L121) than the normal ones, etc.)

**But**, if you figure this out, and it's something that we can easily support (or, would even simplify our path handling), feel free to send a PR.

Best,
Gottfried
