### ISSUE TITLE
Question about SimpleCapture example

### ISSUE THREAD

**Issue by jansensan** [gohai/processing-glvideo#42]
When running the SimpleCapture example on a Raspberry Pi, I ran into an issue where I obtained no error, but only a black window. I am using the Raspberry Pi with Real VNC.

I tried connecting the Pi to my television, and then I managed to see the video output properly.

I don't know/understand much about GL, but am I understanding correctly that this type of output is something that would not be available in a VNC viewer?

**Comment by gohai** [comment]
No, hardware-accelerated video is just not available to the layer VNC is operating at.
