### ISSUE TITLE
having trouble playing multiple videos (more than two) on raspberry pi

### ISSUE THREAD

**Issue by bugingi** [gohai/processing-glvideo#48]
Hello, Thanks for your great library. 
I found that it seems to prevent me from playing more two videos at the same time even though I crank up the GPU memory. (it is probably a fault on my side since I do not have many experience with processing.)

**Comment by gohai** [comment]
No it's probably just maxing out the hardware decoder. I am happy that it works with two even. Upcoming versions of the Raspbian OS will switch to a different video decoding architecture, maybe this will unlock more performance - but for the time being things are the way they are (it's a $25 device).
