### ISSUE TITLE
Implement loadPixels()

### ISSUE THREAD

**Issue by schwamic** [gohai/processing-glvideo#5]
This is not really an issue, but I think it would be very helpful if the _loadPixels()_ could be applied directly to the _GLVideo_.

For example: 

```
import gohai.glvideo.*;
GLvideo video;

void setup(){
    video = new GLVideo(this, "test.mp4");
    video.loop();
}

void draw(){
    video.loadPixels();
    video.pixels[0];
    //do something
}
```

**Comment by gohai** [comment]
Yes, this is on the list to be implemented soon-ish (when I am back from vacation).

**Comment by gohai** [comment]
Partially implemented here - but doesn't work yet (only gives black pixels): https://github.com/gohai/processing-glvideo/commit/bb570c27fa572dd1be59fcf2b885a8f56e59fe4c

Any help would be duly appreciated, not sure when I find time to look into it.

**Comment by codeanticode** [comment]
Tested after applying the fix described [here](https://github.com/processing/processing/issues/4643), and pixels array contains video frame, please confirm.
