### ISSUE TITLE
Can´t configure audio output throught Audio JACK

### ISSUE THREAD

**Issue by Aurelian24** [gohai/processing-glvideo#54]
Can´t configure audio output throught Audio JACK. 

I´ve tryed every single raspian configuration to do it as you can see in this post: 
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=226849&p=1392225#p1392225

I realized that is a problem with this library wich doesn´t have an option to configure the audio throuth audio jack.

Any Idea on how can a make audio came out from Audio Jack Output and NOT from hdmi?

**Comment by gohai** [comment]
This should be fixed in the most recent release, please give it a try.
