### ISSUE TITLE
Question not Issue (Implementation on Windows) 

### ISSUE THREAD

**Issue by f41ardu** [gohai/processing-glvideo#56]
Is it possible to implement this library for Processing on Windows? 
Or I need some advise how to implement an udp camera receiver in Processing on Windows. 
I already tried Daniel Shiffmanns approach without success. And this library start to work with little modification on an Raspberry PI. See https://github.com/f41ardu/TelloProcessing/blob/master/TelloVideoCapture/TelloVideoCapture.pde

Any further hint or advise is much appreciated.

**Comment by gohai** [comment]
Hi, thank you for finding this library useful. I have no plans to port it to Windows though.
