### ISSUE TITLE
Sketch Failing or terminating 

### ISSUE THREAD

**Issue by awilkie1** [gohai/processing-glvideo#57]
Library has been running fine until this week where the sketch seems to crash mid playback or not even load Error attached below. Any ideas would be appreciated.

	0   AppKit                              0x00007fff50dace63 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 378
	1   AppKit                              0x00007fff50daa253 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1479
	2   AppKit                              0x00007fff50da9c86 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 45
	3   libnativewindow_macosx.jnilib       0x000000012eb573fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	4   ???                                 0x000000011bc48a88 0x0 + 4760832648
)
GLVideo: Device enumeration is currently not available on macOS. The device returned is a pure guesstimate.
GLVideo: avfvideosrc0: Internal data stream error.
Debugging information: gstbasesrc.c(2939): void gst_base_src_loop(GstPad *) (): /GstPipeline:pipeline0/GstAVFVideoSrc:avfvideosrc0:
streaming stopped, reason not-negotiated (-4)
Keystone 006
Final caps: video/x-raw(memory:GLMemory), format=(string)RGBA, width=(int)640, height=(int)480, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)30/1, texture-target=(string)2D
Your shader needs to be of COLOR type to render this geometry properly, using default shader instead.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000134bf3c41, pid=689, tid=0x0000000000012107
#
# JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libglib-2.0.0.dylib+0x53c41]  g_slice_alloc+0x1c1
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/ashleywilkie/hs_err_pid689.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.

**Comment by gohai** [comment]
Thanks for the report. Unfortunately, I've decided to remove support for macOS from the library, since I don't have the resources to develop this further. So I fear this won't be addressed.

**Comment by awilkie1** [comment]
Yeah its crashing on RPI also. I can provided the printout there also
