### ISSUE TITLE
How to toggle between 2 videos using Processing on a Raspberry Pi 3

### ISSUE THREAD

**Issue by sanguinity** [gohai/processing-glvideo#59]
Im running Processing 3 on a Raspberry pi 3 and I was trying to use a Keypress sketch to toggle between 2 videos, the thing is the first video is able to switch to the second video but the second video is unable to switch back to the first video

**Comment by gohai** [comment]
Hi @sanguinity - perhaps you find some help on the Processing Forum regarding this issue. From this description alone I can't tell you what is going on (and I also currently have time to work on this library, sorry).
