### ISSUE TITLE
error displayed

### ISSUE THREAD

**Issue by FrankOcean11** [gohai/processing-glvideo#60]
thanks

**Comment by FrankOcean11** [comment]
![20190507_093528](https://user-images.githubusercontent.com/10504709/57310215-052e0300-70af-11e9-9d3c-fb7531662248.jpg)
![20190507_090910_HDR](https://user-images.githubusercontent.com/10504709/57310523-97cea200-70af-11e9-8eba-dbdbb2ae45a6.jpg)

**Comment by gohai** [comment]
@FrankOcean11 In the screenshot you're using Processing's _Video_ library, not _GlVideo_, which is what this repository is about. Please ask similar questions in the Processing Forum in the future.
