### ISSUE TITLE
Gohai.glvideo Not working

### ISSUE THREAD

**Issue by TaynaCT** [gohai/processing-glvideo#62]
I'm trying to compile the basic example of Single Video from the OpenGL video playback for Processing in a Raspberry Pi 3 B+. But video simply doesn't appear. No error logs are displayed. I simply don't understand.

Here is the link of the example I'm using:
https://github.com/gohai/processing-glvideo/blob/master/examples/SingleVideo/SingleVideo.pde

Edit:
 I made a debug to understand what was going on the draw function. The line video.available(), always return false.

**Comment by gohai** [comment]
Try the prepared Raspbian image on pi.processing.org.
